CREATE TABLE patient_info (
    id SERIAL,
    full_url varchar(255),
    p_resource varchar(255),
    request varchar(255),
    resource_type varchar(255),
    resource_id varchar(255),
    meta varchar(255),
    identifier_use varchar(255),
    identifier_system varchar(255),
    identifier_value varchar(255),
    p_status TEXT,
    class_system varchar(255),
    class_code INT,
    type_coding_system varchar(255),
    type_coding_code varchar(20),
    type_coding_display varchar(255),
    type_text varchar(255),
    type_subject_reference varchar(255),
    type_subject_display varchar(255),
    participant_type_coding_system varchar(255),
    participant_type_coding_code varchar(255),
    participant_type_coding_display varchar(255),
    participant_type_coding_text varchar(255),
    participant_type_coding_period_start varchar(255),
    participant_type_coding_period_end varchar(255),
    participant_type_coding_individual_reference varchar(255),
    participant_type_coding_individual_display varchar(255),
    participant_period_start varchar(255),
    participant_period_end varchar(255),
    participant_location_reference varchar(100),
    participant_location_display varchar (100),
    participant_service_provider_reference TEXT,
    participant_service_provider_display TEXT
);

